var userName = document.getElementById('name')
var email = document.getElementById('email')
var password = document.getElementById('password')
var age = document.getElementById('age')
var contact = document.getElementById('contact')
var cnic = document.getElementById('cnic')

var userNameError = document.getElementById('nameError')
var emailError = document.getElementById('emailError')
var passwordError = document.getElementById('passwordError')
var ageError = document.getElementById('ageError')
var contactError = document.getElementById('contactError')

console.log(userName)
console.log(password)
console.log(age)
console.log(contact)
console.log(email)
console.log(userNameError)
console.log(passwordError)
console.log(emailError)
console.log(ageError)
console.log(contactError)